#dns_name       = "puff.awssolutionsprovider.com"
aws_access_key        = "AKIAYSTYJMCNP4PF33M7"
aws_secret_key        = "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"
region                = "us-east-2"
rancher_masters_count = "3"
# vm_count       = 4
# volume_size    = 20
# machine_type   = "t2.micro"
# machine_ports  = [22, 80, 443, 6443]
# image_id       = "ami-069acc051e43a100a"
# allow_tls      = "allow_tls-rnchr-2"
# key_pair       = "terraform_key-rnchr-2"
